### ISSUE TITLE
LDAC 

### ISSUE THREAD

**Issue by Anubiz88** [AndroidAudioMods/ViPER4Android#15] opened 2023-01-19 14:50 UTC
2.0 working flawlessly on Pixel 6a and Poco F2 pro. However using headphones that support LDAC, makes the app stop recognising that the driver is installed.

**Comment by Iscle** [comment] 2023-01-19 20:22
Hi!

Thanks for the feedback. 

Do you know how to take a logcat? 

It would be useful to determine which configuration the Android system is sending to ViPER.

You can upload a file or paste it into a [gist](https://gist.github.com)

**Comment by Iscle** [comment] 2023-01-19 20:29
Duplicate of #5

**Comment by Anubiz88** [comment] 2023-01-21 16:54
I will look into providing a logcat in the following days. For now the only thing ive noticed by tinkering in android developer settings is that lowering the sample rate fixes the issue(kind of kills the point of LDAC however).

**Comment by Iscle** [comment] 2023-01-25 00:52
What sample rate are you having the issue with?

**Comment by Iscle** [comment] 2023-02-21 17:54
Hi @Anubiz88, any updates on this?

**Comment by iscle** [comment] 2023-05-21 23:32
Fixed in v0.4.0.

**Closed by iscle** 2023-05-21 23:32 UTC
Labels: duplicate, enhancement
